### ISSUE TITLE
Config File

### ISSUE THREAD

**Issue by cargueta001** [aarons22/homebridge-bond-v2#1]
@aarons22 Thank you for taking the time to build this repo. 

I had initially done this via the IFTTT with BOND but I would gladly try this however I would like to see the steps you took with screen grabs perhaps? The Readme is throwing me off with the token request.

Thanks in advance.

**Comment by aarons22** [comment]
@cargueta001 Good idea! I updated the README with an app screenshot. Turns out you can just grab the token there
