### ISSUE TITLE
Error Not Found

### ISSUE THREAD

**Issue by cargueta001** [aarons22/homebridge-bond-v2#2]
@aarons22 I followed the steps and updated the firmware. However, my terminal is showing error codes. Please see the attachments. These were the same issues I came across with the other plugin unfortunately. Thanks in advance!
![2B093117-E9D6-472A-94D8-D60A1CE3992C](https://user-images.githubusercontent.com/48275759/65391952-23299680-dd24-11e9-80ae-2f3024a460bb.png)
![6AF88D85-0519-449A-8439-091FF6CA20CE](https://user-images.githubusercontent.com/48275759/65391953-23299680-dd24-11e9-8d79-11fb537e8b7c.png)

**Comment by aarons22** [comment]
@cargueta001 Yeah I'm seeing the issue intermittently on my end. I think the solution is to use the IP Address of the Bond instead of the ID. I've added to my list!

**Comment by aarons22** [comment]
Just published 0.2.0, which uses the IP Address instead of the BondID. Seems to be working on my homebridge server and it's actually _alot_ more responsive now 🎉

**Comment by cargueta001** [comment]
@aarons22 After some troubleshooting, I found that the config needs to be labeled as "bond_ip_address" NOT "id" as it will continue to repeat errors. Otherwise, the Home app comes up with all devices! Thank you!

**Comment by aarons22** [comment]
Ahh good catch on the README. I’ve fixed the typo!
