### ISSUE TITLE
Error: getaddrinfo ENOTFOUND undefined undefined:80

### ISSUE THREAD

**Issue by jimboslicethat** [aarons22/homebridge-bond-v2#3]
Hey there! First off thank you for going through the work of getting the homebridge bond plugin working with the V2 API. I'd really like to add this plugin to my setup. I am experiencing the following issue when trying to install your plugin
<img width="957" alt="Screen Shot 2019-09-22 at 2 36 21 PM" src="https://user-images.githubusercontent.com/8390638/65394095-96dc9b00-dd46-11e9-82ab-b728d32653da.png">

I've double and triple checked my Bond ID and my Bond Token. But I don't have enough context to understand what is happening here. Thanks for your help in advance.

**Comment by aarons22** [comment]
Hey! Someone else had a similar issue (I saw it locally a few times as well) so I switched to using the IP address of the Bond. Update to 0.2.0 and you should be gtg 👌

README has also been updated with the new config parameter!

**Comment by jimboslicethat** [comment]
Thank you for your help! And also thanks for your work on making this plugin work again properly.
